### ISSUE TITLE
"Error while starting streaming server" with external players

### ISSUE THREAD

**Issue by Kabouik** [Stremio/stremio-shell#97] opened 2019-09-22 00:15 UTC
When I try to stream a video from a torrent file in mpv as external player (right click in the Stremio builtin player, play in mpv), I get the following error:

```
Error while starting streaming server. Please consider re-installing Stremio from 
Stremio streaming server has thrown an error from https://www.stremio.com

QProcess::ProcessError code: 1

(node:9783) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
fs.js:127
    throw err;
    ^

Error: EACCES: permission denied, open '/opt/stremio/../../subtitles.srt'
    at Object.openSync (fs.js:448:3)
    at Object.writeFileSync (fs.js:1248:35)
    at IncomingMessage.<anonymous> (/opt/stremio/server.js:132655:36)
    at IncomingMessage.emit (events.js:214:15)
    at IncomingMessage.EventEmitter.emit (domain.js:476:20)
    at endReadableNT (_stream_readable.js:1178:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/opt/stremio/../../subtitles.srt'
}
```
Please note that streaming does work in the builtin Stremio player. It also works *sometimes* in mpv, but the mpv window may eventually close with no error, and then the message will appear every time I try to play the movie in mpv again, even after restarting Stremio (while the builtin player will still work). This pattern with mpv first working temporarily and then failing all the time made me think maybe the issue was related to the cache, but deleting the content of the cache folder right after getting the issue and restarting Stremio did not solve it: the error popped up immediately when trying to play in mpv again. 

I get the exact same error when trying to play in vlc as external player, so the issue is probably not with the player itself.

Any ideas?

### Versions
Stremio 4.4.77 installed from AUR.
Web UI 4.4.95
Server 4.6.0

**Comment by TRtomasz** [comment] 2021-07-08 08:41
This was caused by subtitles and has been fixed in the last release.

**Closed by TRtomasz** 2021-07-08 08:41 UTC

**Comment by Kabouik** [comment] 2021-07-08 09:09
Thanks!

I feel guilty because I eventually understood that this was caused by subtitles (external ones, not embedded ones) but I totally forgot about this issue I opened so I didn't think about updating it. Sorry, this could perhaps have facilitated the fix.

**Comment by boussou** [comment] 2021-07-16 08:41
I just searched in server.js every occurence of __dirname + '/../../subtitles.srt')  and replaced it by '/tmp/subtitles.srt'
(there is 2 occurrence). Will work for any version of Linux

**Comment by rdantas03** [comment] 2021-12-14 05:02
> This was caused by subtitles and has been fixed in the last release.

Nope. It happens all time, whith every Stremio version installed.
